### ISSUE TITLE
"manhole-cli" is eating 6% of my CPU being just idle

### ISSUE THREAD

**Issue by jcea** [ionelmc/python-manhole#44]
Manhole 1.5.0. Ubuntu 16.04.

Steps to reproduce:

1. Use "manhole-cli" to connect to a process.
2. Do "top" in another terminal. Observe "manhole-cli" eating a lot of CPU doing nothing. In my case, 6% of my CPU is being burned for no reason.
3. "strace -f -p PID" shows a flood of this:

```
[...]
[pid 14394] poll([{fd=4, events=POLLIN|POLLPRI|POLLERR|POLLHUP}, {fd=3, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 2, 1) = 0 (Timeout)
[pid 14394] poll([{fd=4, events=POLLIN|POLLPRI|POLLERR|POLLHUP}, {fd=3, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 2, 1) = 0 (Timeout)
[pid 14394] poll([{fd=4, events=POLLIN|POLLPRI|POLLERR|POLLHUP}, {fd=3, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 2, 1) = 0 (Timeout)
[...]
```

**Comment by nirs** [comment]
Hi @jcea, can you test the fix?

**Comment by jcea** [comment]
@nirs, I was about to send a similar pull request. 

The patch works fine. "manhole-cli" is not standing out in my "top".

Thanks.
