### ISSUE TITLE
Travis tests fail python 2.6/3.3

### ISSUE THREAD

**Issue by nirs** [ionelmc/python-manhole#47]
2.6 tests fail:
https://travis-ci.org/ionelmc/python-manhole/jobs/319757847

3.3 tests fail:
https://travis-ci.org/ionelmc/python-manhole/jobs/319757943

Looks like 2.6 and 3.3 are not supported now in pytest, I think we should remove these tests.

**Comment by ionelmc** [comment]
I agree.
