### ISSUE TITLE
eventlet tests fail with "RuntimeError: no suitable implementation for this system"

### ISSUE THREAD

**Issue by nirs** [ionelmc/python-manhole#49]
```
File "/home/travis/build/ionelmc/python-manhole/.tox/2.7-signalfd-eventlet-nocov-patchthread/lib/python2.7/site-packages/eventlet/support/monotonic.py", line 167, in <module>
    raise RuntimeError('no suitable implementation for this system')
RuntimeError: no suitable implementation for this system
```

https://travis-ci.org/ionelmc/python-manhole/builds/319810334

**Comment by ionelmc** [comment]
It appears they have a fix but it's not in any release yet: https://github.com/eventlet/eventlet/commit/b756447bab51046dfc6f1e0e299cc997ab343701

**Comment by nirs** [comment]
Lets mark the eventlet tests as xfail until we have a fix?

**Comment by ionelmc** [comment]
Perhaps it's better to use travis' `allow_failures` option. Or just pin the master of eventlet? Hmmm

**Comment by nirs** [comment]
How can we pin to eventlet master?

**Comment by ionelmc** [comment]
Actually I have a better idea: just add the workaround in the helper module. And document the problem I guess?

**Comment by nirs** [comment]
If it works, this looks like the best option.
