### ISSUE TITLE
Latest release not corrently updated

### ISSUE THREAD

**Issue by jcea** [ionelmc/python-manhole#61]
In https://github.com/ionelmc/python-manhole/releases and https://github.com/ionelmc/python-manhole , latest release is shown as 1.0.0, from 2015.

**Comment by ionelmc** [comment]
Is it still worth doing? I have to manually click through that ui to add those release notes. All the tags are here:
![image](https://user-images.githubusercontent.com/129501/112278822-e6798b00-8c8b-11eb-903c-005ccff09d49.png)

**Comment by jcea** [comment]
Convenient. Not doing it is confusing. I noticed, as you can see.

**Comment by ionelmc** [comment]
Alright fine, did some copypasta.
