### ISSUE TITLE
Under Python 3.11, manhole doesn't flush stdout until a statement is entered

### ISSUE THREAD

**Issue by jcea** [ionelmc/python-manhole#66]
Until Python 3.11, any output produced by the daemon was visible in the client CLI in real time. Now (Python 3.11)  I only see daemon stdout after I type something in the client CLI and press enter.

Seems like "flush" is not behaving like it was behaving before.

**Comment by ionelmc** [comment]
Next release will have a fix for this.

**Comment by jcea** [comment]
Sorry, I just upgraded to manhole 1.8.1 and I experiment the same issue. I don't see any improvement at all.

The output is still buffered in my application.

**Comment by jcea** [comment]
I have a trivial test. Run this code in a window:

```
#!/usr/bin/env python3

import sys
import os
import time

import manhole

manhole.install()

for i in range(99999):
    print(f'print: {i}')
    os.write(1, b'write: ' + repr(i).encode('utf-8') + b'\n')
    time.sleep(1)
```

This script will print each  number twice, once per the ```print``` and once because the ```write```. Good so far.

Launch now in a different window ```manhole-cli``` to connect to this process.

In the first window we now only see the ```write``` numbers, but no the ```print``` numbers. Good, because manhole is sending the ```prints``` to stdout to ```manhole-cli``` in the other window.

When running the program with Python < 3.11, in ```manhole-cli``` window we see the ```print``` numbers immediately, simultaneously with the ```write``` numbers in the first window. Perfect.

But if we use Python >= 3.11, we don't see anything at all in the ```manhole-cli``` window until you do something in the terminal, like just pressing enter, or until a big buffer somewhere is filled. At that moment, ```print``` numbers buffered are displayed.

I can not reopen this issue. Should I open a new one?

Thanks, @ionelmc .
