### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by brianjmurrell** [ionelmc/python-manhole#68]
It seems it has been over 3 years since there has been an updated release of this module.

In the current release, the SPDX license expression is incorrect.

Could we please get a new release fixing at least that so that tools that need to parse the license are able to do so?

Thanks in advance.

**Comment by nirs** [comment]
@brianjmurrell do yo want to send a PR fixing the SPDX issues or provide more details on the issue?

**Comment by brianjmurrell** [comment]
I was sure I replied to this already.  Maybe sitting somewhere on a computer waiting for me to hit _send_.  :frowning: 

In any case, everything on master is already fixed.  It just needs a release please and thanks, in advance.

**Comment by ionelmc** [comment]
Will make.

**Comment by brianjmurrell** [comment]
Have you been able to make any progress here?  It should be a very simple change.  If making a new release from master is proving to be too difficult, perhaps the easiest thing to do is to branch https://github.com/ionelmc/python-manhole/tree/v1.8.0 and apply the simple license fix there and then release v1.8.1.

**Comment by brianjmurrell** [comment]
Awesome, thanks!
